[package]
name = "emergency-compliment"
version = "0.1.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
repository = "https://github.com/ashleygwilliams/rust-emergency-compliment"

[dependencies]
pencil = { git = "https://github.com/fengsp/pencil.git" }
motivations = "1.0.2"
